"use client";

/// Trade-stat matcher index over `public/trade-stats.json` (generated by the
/// `fetch-trade-stats` pipeline tool; regenerable, gitignored). Each stat
/// carries matcher templates where `#` stands for a number — an item line
/// "+85 to maximum Life" normalized equals the template "+# to maximum Life"
/// normalized (both fold to "# to maximum life"). A leading `+` is
/// decoration and folds into the placeholder; `-` is semantic and stays
/// literal so "-13%…" lands on the `-#%…` (negate) template, mirroring
/// Exiled-Exchange-2's matcher data. Keys are case-folded — the scraped
/// matcher casing drifts from clipboard text ("Maximum" vs "maximum").

export interface TradeStatMatcher {
  string: string;
  /** Pinned value — the matcher applies only when the line's single number
   * equals it (e.g. the "# Charm Slot" singular form, value 1). */
  value?: number;
  /** The displayed number is the negation of the stat's canonical value. */
  negate?: boolean;
}

export interface TradeStat {
  ref: string;
  /** 1 → higher is better; -1 → lower is better. */
  better: number;
  matchers: TradeStatMatcher[];
  /** Bucket ("explicit" | "pseudo" | "implicit" | …) → trade stat ids. */
  ids: Record<string, string[]>;
}

export interface TradeStatsFile {
  version: number;
  source: string;
  generated: string;
  stats: TradeStat[];
}

/** One (stat, matcher) pair filed under the matcher's normalized template. */
export interface IndexedStat {
  stat: TradeStat;
  matcher: TradeStatMatcher;
}

export interface LineMatch {
  stat: TradeStat;
  /** The line's numbers in order (negated for `negate` templates). */
  values: number[];
  matchedBy: "template" | "exact-value";
}

// Trailing tags the game appends to stat lines — same set the Rust parser's
// `strip_trailing_tags` handles, plus `(desecrated)`.
const TAG_RE = /\s*\((?:fractured|rune|enchant|desecrated|crafted|implicit)\)$/i;

const NUM_RE = /\d+(?:\.\d+)?/g;

// PoE's "advanced" tooltip format prints the rolled value followed by the mod's
// possible range, e.g. `+61(60-69) to maximum Life`, `24(20-30)% increased …`,
// `Has 3(1-3) Charm Slots`. The parenthetical range describes the mod, not the
// actual roll, so it must be removed BEFORE numbers are templated — otherwise
// `+61(60-69) to maximum Life` normalizes to `#(#-#) to maximum life`, which
// matches no template (the bug that left every gear line "no trade id").
// Matches a `(min-max)` or single `(n)` immediately following a digit.
const ROLLED_RANGE_RE = /(\d)\((?:\d+(?:\.\d+)?)(?:-\d+(?:\.\d+)?)?\)/g;

/** Drop advanced-format roll ranges, keeping the displayed (actual) value. */
export function stripRolledRanges(line: string): string {
  return line.replace(ROLLED_RANGE_RE, "$1");
}

/** Strip trailing `(fractured)`-style tags (they can stack) + roll ranges. */
export function stripLineTags(line: string): string {
  let text = stripRolledRanges(line.trim());
  for (;;) {
    const next = text.replace(TAG_RE, "");
    if (next === text) break;
    text = next.trimEnd();
  }
  return text;
}

/** Normalize a stat line (or matcher template) to an index key: numeric
 * magnitudes → `#`, `+#` folds to `#` (minus stays literal), whitespace
 * collapsed, trailing tags + roll ranges stripped, case-folded. */
export function normalizeLine(line: string): string {
  return stripLineTags(line)
    .replace(NUM_RE, "#")
    .replace(/\+#/g, "#")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

/** The line's numeric magnitudes in order (what each `#` stands for). */
export function lineValues(line: string): number[] {
  return [...stripLineTags(line).matchAll(NUM_RE)].map((m) => Number(m[0]));
}

/** Index every (stat, matcher) pair by the matcher's normalized template. */
export function buildIndex(stats: TradeStat[]): Map<string, IndexedStat[]> {
  const index = new Map<string, IndexedStat[]>();
  for (const stat of stats) {
    for (const matcher of stat.matchers) {
      const key = normalizeLine(matcher.string);
      const bucket = index.get(key);
      if (bucket) bucket.push({ stat, matcher });
      else index.set(key, [{ stat, matcher }]);
    }
  }
  return index;
}

/** Match one item line against the index. Value-pinned matchers are more
 * specific, so they win over plain templates sharing the same key. */
export function matchLine(
  index: Map<string, IndexedStat[]>,
  line: string,
): LineMatch | null {
  const candidates = index.get(normalizeLine(line));
  if (!candidates) return null;
  const numbers = lineValues(line);

  for (const { stat, matcher } of candidates) {
    if (matcher.value === undefined) continue;
    // Exact-text matchers (no number on the line) imply their pinned value.
    if (numbers.length === 0 || (numbers.length === 1 && numbers[0] === matcher.value)) {
      return { stat, values: [matcher.value], matchedBy: "exact-value" };
    }
  }
  for (const { stat, matcher } of candidates) {
    if (matcher.value !== undefined) continue;
    return {
      stat,
      values: matcher.negate ? numbers.map((n) => -n) : numbers,
      matchedBy: "template",
    };
  }
  return null;
}

let cached: TradeStatsFile | null = null;
let loading: Promise<TradeStatsFile | null> | null = null;

/** Load (and cache) `trade-stats.json`. Returns `null` when absent. */
export async function loadTradeStats(): Promise<TradeStatsFile | null> {
  if (cached) return cached;
  if (loading) return loading;
  loading = (async () => {
    try {
      // `no-cache` revalidates — the file changes whenever the operator
      // re-runs fetch-trade-stats, and a stale copy hides new stats.
      const r = await fetch("/trade-stats.json", { cache: "no-cache" });
      if (!r.ok) return null;
      cached = (await r.json()) as TradeStatsFile;
      return cached;
    } catch {
      return null;
    } finally {
      loading = null;
    }
  })();
  return loading;
}
